on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
          TARGET_PATHS: README.md, ./1-template-syntax/README.md, ./2-template-syntax/README.md, ./3-vue-instance-structure/README.md, ./4-vue-cli/README.md
          TOC_TITLE: '目次'